### ISSUE TITLE
Ability to customize underlying components during setup

### ISSUE THREAD

**Issue by ConnerPetzold** [Zheoni/bevy_pixel_buffer#1]
It would be great to be able to modify things like the transform and sprite components when the PixelBuffer is created. What if instead of using `SpriteBundle`, there's `PixelBufferBundle` that replaces the current tuple bundle and surfaces components users are likely to want to customize. An example is the `ShapeBundle` in `bevy_prototype_lyon`: https://github.com/Nilirad/bevy_prototype_lyon/blob/master/src/entity.rs#L23

That way sensible defaults can still be provided and there can still be a builder API, but if you still have access to all of the components that are currently hidden in `SpriteBundle`.

The exposed API could look something like this:
```rust
let size = PixelBufferSize::size((100, 100));
let image = PixelBuffer::create_image(size, |frame| { frame.per_pixel(|_, _| Pixel::RED) });

commands.spawn_bundle(PixelBufferBundle {
  size,
  texture: images.add(image),
  transform: Transform::from_xyz(10., 10., 0.),
  sprite: Sprite {
    anchor: Anchor::BottomLeft,
    ..default()
  },
  ..default()
});
```

**Comment by ConnerPetzold** [comment]
The thing I'm not sure about is how the non-sprite usage of the library fits in with this. What did you have in mind for non-sprite usage? Would it use a custom bevy renderer instead?

**Comment by Zheoni** [comment]
What I'm thinking and implementing is this
```rust
/// Render setup configuration
#[derive(Clone, Debug)]
pub enum RenderConfig {
    /// Set up a sprite and an optional 2D camera
    AsSprite {
        /// Spawn a 2D camera
        spawn_camera: bool,
        /// Custom sprite bundle parameters.
        ///
        /// Different from [SpriteBundle] because [SpriteBundle] some extra fields that are not customisable.
        sprite_bundle: CustomSpriteBundle,
    },
}
```
`CustomSpriteBundle` maps all the customisable fields of SpriteBundle. The onyl not customisable fields are the texture and the sprite custom size.

I'm also making possible to use a bundle instead of the builder pattern.

---

`RenderConfig` is an enum to support future alternative ways of rendering. In the future I intended to implement a custom renderer that did't use the bevy one, like `pixels` does, so if the pixel buffer is the only thing rendering there's no overhead.

**Comment by ConnerPetzold** [comment]
For the texture, are there things you could potentially change about the `Image` and still have the buffer work fine? I wonder if instead of hiding it completely during setup, you could provide a helper function to create an Image that works well for the pixel buffer and maybe assert certain conditions in systems that interact with the `Image`. I think that works better because nothing is stopping the user from customizing any of these components in their own systems.

Similarly for `Sprite.custom_size`, maybe it could be added in a startup system?

---

I don't know too much about custom Bevy renderers, but how would the components be involved? If you were doing it like `bevy_pixels`, then you wouldn't have a set of components at all, but rather the plugin would expose the frame buffer as a resource and would just define systems for rendering.

**Comment by Zheoni** [comment]
That's exactly what I have done. I new utility function and I also implemented a couple of bundles in case the user does not like the builder pattern.

I'm still fixing a couple of edge case bugs, but I think the changes will be pushed soon (tomorrow probably).

Regarding the rederers, neither do I, but having this API allows to add more if needed in the future.

**Comment by ConnerPetzold** [comment]
Hmm I'm confused, why do you need `CustomSpriteBundle` then? I would think with the utility function to create the `Image` that you could supply the texture directly?

**Comment by Zheoni** [comment]
Ok, changes made. `CustomSpriteBundle` is for the builder. The bundle to create the pixel buffer manually is `PixelBufferSpriteBundle` that contains a normal bevy `SpriteBundle`. There are a couple new examples.

I want to rethink the `query` module before a new release. Shouldn't take too long.

**Comment by ConnerPetzold** [comment]
Ohh gotcha, makes sense! 👍

**Comment by ConnerPetzold** [comment]
Great work on the refactor.

Is this how you would recommend initializing the frame with the bundle approach?
```rust
let image_handle = create_image(...);
let mut frame = Frame::extract(&mut images, &image_handle);
frame.per_pixel(...)

commands.spawn_bundle(PixelBufferSpriteBundle { ... });
```

**Comment by Zheoni** [comment]
Yes, that is how to initialize the frame with the bundle approach. But that made me think if `create_image` returned the image itself instead of the handle. In that case a bundle without initalization would be:
```rust
commands.spawn_bundle(PixelBufferSpriteBundle {
  pixel_buffer: ...,
  sprite_bundle: SpriteBundle {
    texture: images.add(create_image(...)), // user needs to add the image
    ...
});
```

And the initalization:
```rust
let mut image = create_image(...);
let mut frame = Frame::get(&mut image);
frame.per_pixel(...);
let image_handle = images.add(image);

commands.spawn_bundle(PixelBufferSpriteBundle { ... });
```

What do you think is better, how it is currently or if `create_image` returned the image instead of the handle?

**Comment by ConnerPetzold** [comment]
Oh yeah I think returning the Image looks good here. I think it's a bit more flexible and looks better for this case of initializing the frame. In my initial example I had thought about letting the user pass in a frame initializer to create_image itself -- how do you feel about that?
```rust
let image = create_image(size, |frame| { frame.per_pixel(|_, _| Pixel::RED) });
```

**Comment by Zheoni** [comment]
Not everyone would want to initalize the image in or just after `create_image`. I think for most people it would be fine it the image is not initialised and they just get a frame in their regular update system.

For now I will change `create_image` to return the image and add convenience traits to do something like

```rust
let mut image = create_image(...);
image.edit_frame(|frame| frame.per_pixel(|_, _| Pixel::RED));
```

**Comment by ConnerPetzold** [comment]
Could the convenience traits go even further to just implementing the frame functions on Image itself? Something like this:
```rust
image.per_pixel(|_, _| Pixel::RED);
```

Maybe that's taking the convenience too far but it could be an interesting separate API for just manipulating bevy images.

**Comment by Zheoni** [comment]
Could be done but I prefer to explicitly get the `Frame` because it's a reinterpretation of the `Image`. The image has a `Vec<u8>` for the data and the `Frame` interprets it as a `&[Pixel]`

**Comment by ConnerPetzold** [comment]
I was actually wondering -- is it expensive to re-create the Frame every tick -- could it be stored in the PixelBuffer component if so?

**Comment by Zheoni** [comment]
I believe it is practically free to build the Frame every tick. However, you could benchmark it just in case.
