### ISSUE TITLE
fill_egui example not working

### ISSUE THREAD

**Issue by KirkBuah** [Zheoni/bevy_pixel_buffer#13]
I'm trying to run the example with bevy 0.12.1, bevy_pixel_buffer 0.6.1 and bevy_egui 0.24.

This is the error i get:

```
error[E0599]: no method named `update_fill_egui` found for struct `bevy_pixel_buffer::query::QueryPixelBuffer<'_, '_>` in the current scope
  --> src\main.rs:32:12
   |
32 |         pb.update_fill_egui(ui.available_size());
   |            ^^^^^^^^^^^^^^^^ method not found in `QueryPixelBuffer<'_, '_>`

```

**Comment by Zheoni** [comment]
The `egui` feature is disabled by default. If you are running the example directly you need to pass `--features "egui"` or if you added `bevy_pixel_buffer` to your `Cargo.toml` you need to enable the feature like

```toml
[dependencies]
bevy_pixel_buffer = { version = "0.6.1", features = ["egui"] }
```

Does this solve the problem?

**Comment by KirkBuah** [comment]
The new error is now:

```
error[E0308]: mismatched types
   --> src\main.rs:32:29
    |
32  |         pb.update_fill_egui(ui.available_size());
    |            ---------------- ^^^^^^^^^^^^^^^^^^^ expected `Vec2`, found `bevy_egui::egui::Vec2`
    |            |
    |            arguments to this method are incorrect
    |
    = note: `bevy_egui::egui::Vec2` and `Vec2` have similar names, but are actually distinct types

```

Which i don't fully understand, since both are the same type

**Comment by Zheoni** [comment]
Ok, that's because bevy_egui has not been updated in this crate. You have to use the same version of `bevy_egui` and it's outdated here. I will update the `bevy_egui` required version with the next `bevy` release, so until then you have to use `bevy_egui` version, `0.23`

**Comment by KirkBuah** [comment]
Thank you for your answer.
Sadly i still get an error:

```
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
  |
  = note: "x86_64-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-v... (it's very long)
  = note: ld: cannot find -lshlwapi: No such file or directory
```

I tried googling it and i think it has something to do with [the way rustup was installed](https://github.com/emilk/egui/issues/2856).

I'll try reinstalling it tomorrow and i'll let you know if it works.

**Comment by KirkBuah** [comment]
Ok i reinstalled rustup and it works as intended now. Thanks!

**Comment by Zheoni** [comment]
Awesome! Have fun with bevy 😄

**Comment by fwolfst** [comment]
> Awesome! Have fun with bevy 😄

@Zheoni 

To someone not familar with crates and features (e.g. no idea how to list them), this was confusing me too. Would you accept a PR that adds these instructions to the README?

**Comment by Zheoni** [comment]
@fwolfst Sure, I accept PRs! 😄 I also just noticed now that bevy had another update. I don't use this anymore so I don't even know when it's time to update things.

**Comment by fwolfst** [comment]
@Zheoni Ya. I couldn't make it work with bevy 15 . Do you use anything similar now?

**Comment by fwolfst** [comment]
@Zheoni Done in https://github.com/Zheoni/bevy_pixel_buffer/pull/20
