### ISSUE TITLE
Adjust pixel size

### ISSUE THREAD

**Issue by KirkBuah** [Zheoni/bevy_pixel_buffer#14]
Hi! I'm opening an issue as i can't find a way to open a discussion.
Is there a way to manually adjust the `PixelBufferSize` from one of the bevy systems?
I tried fiddling with `QueryPixelBuffer` but i cannot seem to find a way to do it except for `.update_fill_egui()` which, from my understanding, also adds new pixels to the pixel buffer (something i don't want to do).
Thank you in advance!

**Comment by Zheoni** [comment]
Maybe this example will help https://github.com/Zheoni/bevy_pixel_buffer/blob/main/examples/resize.rs

If it does not, I will have a look a it next week.

**Comment by KirkBuah** [comment]
This helped me, thank you!
